# Generated by Django 4.2.30 on 2026-05-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('LOGIN_FAILED', 'Échec de connexion'), ('UPLOAD', 'Téléversement'), ('DOWNLOAD', 'Téléchargement'), ('DELETE', 'Suppression'), ('EXPORT', 'Export RGPD'), ('DELETE_ACCOUNT', 'Suppression de compte')], max_length=20),
        ),
    ]
